# -*- coding: utf-8 -*-
"""Lesson7_Bai06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1px3XEcd73PqvlDvw01eznH3xfORIrn6Q
"""



"""Bài 06: Viết chương trình in ra phần tử thứ 4 và phần tử thứ 4 từ cuối lên trong một tuple."""

my_tuple = (1,2,3,4,5,6)
print(my_tuple[4])
print(my_tuple[-4])

