# -*- coding: utf-8 -*-
"""Lesson4_Bai2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fCWSm8CVeA2Ztoci9DXkI75e_bH30nE4
"""



Bài 02. Lập chương trình tính các tổng sau:
     S_1 = 1 + x + x^2 + x^3 + ... + x^n
    S_2 = 1 - x + x^2 - x^3 + ... + (-1)^n.x^n
    S_3 = 1 + x/1! + x^2/2! + ... + x^n/n!

import math
n = int(input("Enter number n "))
x = float(input("Enter number x: "))
S1 = 0
S2 = 0
S3 =  0
for i in range(n+1):
  S1 = S1 + x**i
  S2 = S2 +((-1)**i)*x**i
  S3 = S3+x**i/(math.factorial(i))
  
print(S1)
print(S2)
print(S3)

