# -*- coding: utf-8 -*-
"""Lesson7_Bai10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ENcRearolT5sTw_9pnWIA4TgQ47u4IO
"""



"""Bài 10: Cho list sau: ["www.hust.edu.vn", "www.wikipedia.org", "www.asp.net", "www.amazon.com"]. Viết chương trình để in ra hậu tố (vn, org, net, com) trong các tên miền website trong list trên."""

my_list =  ["www.hust.edu.vn", "www.wikipedia.org", "www.asp.net", "www.amazon.com"]
for item in my_list:
  print(item[-3:])

