# -*- coding: utf-8 -*-
"""Lesson8_Bai01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e9H1tVoAaGytpeWeWXPuaIUwo5-j98-m
"""



"""Bài 01. Viết chương trình tìm giá trị lớn nhất và giá trị nhỏ nhất trong các value của dict"""

my_dict ={
    1 : 5,
    2 : 9,
    3 : 10,
    4 : 20,
    5 : 32
}
max_value = max(my_dict.values())
min_value = min(my_dict.values())
print(f"largest value of dictionary is {max_value}")
print(f"smallest value of dictionary is {min_value}")