# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGOinA0sPETB9Yup5oDwsfxWGcGda5y4
"""



"""Bài 04. Lập trình thực hiện các công việc sau:
    1. Nhập 3 số a, b, c bất kì
    2. Hãy kiểm tra xem ba số đó có phải là độ dài của các cạnh của một tam giác hay không?
    3. Nếu đúng là tam giác thì xác định là tam giác vuông hay không?
"""

a = int(input("Enter verticle a: "))
b = int(input("Enter verticle b: "))
c = int(input("Enter verticle c: "))
if a + b > c and b + c > a and a + c > b:
  print("This is triangle, check if triangle is right angle triangle or not")
  if a == b and a == c and b == c:
    print("This is an equilateral triangle")
  elif a == b and a ==c :
    print("This is isosceles triangle")
  elif c*c == (a*a+b*b) or a*a == b*b + c*c or b*b == a*a + c*c :
    print("This is right angle triangle")

  

else:
  print("This is not triangle")