# -*- coding: utf-8 -*-
"""Lesson6_Bai06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4W9m0tOeiCK_8xuLL97Jt80yih_zJnZ
"""



"""Bài 06. Viết chương trình đếm các chuỗi trong một list thỏa mãn:
        + Độ dài từ 2 trở lên
        + Ký tự đầu tiên và cuối cùng của chuỗi đó giống nhau
"""

my_list = ['Hung', 'Manh', 'P', 'PlusPlus','PPPP']
count = 0
for item in my_list:
  if len(item) >= 2 and item[0] == item[-1]:
    count = count + 1
print(f"there are {count} item")