# -*- coding: utf-8 -*-
"""Lesson12_Bai12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVZRJ2k0UOZwKLLhSSog2tdmcQJf9m4Y
"""

#different_update()
a = {1,2,3,4}
b = {1,5,8,4}
a.difference_update(b)

print(a)

#set.intersection_update(other_set)
nums = {1, 2, 3, 4, 5 }
oddNumbs = {1, 3, 5, 7, 9}
nums.intersection_update(oddNumbs)
print(nums)

#set.isdisjoint(other_set)

nums.isdisjoint(oddNums)
print(nums)

#set.issubset(other_set)

nums.issubset(oddNums)
print(nums)

#set.issuperset(other_set)
nums.issuperset(oddNums)
print(nums)

#set.symmetric_difference_update(other_set)
nums.symmetric_difference_update(oddNums)
print(nums)