# -*- coding: utf-8 -*-
"""Lesson7_Bai00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3lPqZhEqIMYY3s0D4Mh8bVUvpsHrBmE
"""

a, b, c, d = 2, 3, 'hi', 10
print(a)
print(b)
print(c)
print(d)

