# -*- coding: utf-8 -*-
"""Lesson2_Bai2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14sOvtorkXISKluWxbHGilN5FbGR6Kilw
"""

print(type(2.5))
print(type(2))
print(type(6+9j))
print(type(6>9))
lst1 =[1,2,3,4]
print(type(lst1))
set1= {1,2,3,4}
print(type(set1))
tuple1= (2,3,4,5)
print(type(tuple1))
str1 = "Hung"
print(type(str1))
dict1= {'PlusPlus':'Classmate', 'Teacher':'HoanPham'}
print(type(dict1))

"""




*   Number: int,float,complex

*  boolean: True, False

*   Sequence: list, tuple, Set, Strubg, Range


*   Dictionary





"""