# -*- coding: utf-8 -*-
"""Lesson9_Bai04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KhAgO7FWMZcXLlm3W0KxWzDFQu4sAFPo
"""

def is_prime(number):
  if n <= 1:
    return False
  elif n == 2:
    return True
  else:
    for i in range(2,n):
      if n % i == 0:
        return False
    return True
    

def check_prime(n):
  not_Prime = False
  n = int(input("Enter number to see if number is prime or not: "))
  while True:
    for i in range(n):
      if n % i == 0 and i > n:
        not_Prime = True

Primecheck = check_prime(2)
is_Prime = is_prime(n)
print(is_Prime)