# -*- coding: utf-8 -*-
"""Lesson11_Bai01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tqa-KYY8bQQWrQfqTLLS9NaePok5IjV-
"""

class Dog:
  def __init__(self, name, age):
    self.name = name 
    self.age = age

  def get_biggest_number(self, *age):
    oldest = max(*age)
    return f"The oldest dog is {oldest} years old"

Fake = Dog('Fake', 2)
Mickey = Dog('Mickey', 7)
Fuk = Dog('Fuk', 5)

Dog.get_biggest_number(2,5,7)

