# -*- coding: utf-8 -*-
"""Lesson7_Bai07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GEqaV2rtn2zna5qPu9YeCEQsT-pgPMPy
"""



"""Bài 07: Viết chương trình kiểm tra 2 tuple có phần tử chung hay không."""

my_tup1 = (1,2,3,4)
my_tup2 = (1,4,6,7)
Is_sameitem = False
for item in my_tup1:
  if item in my_tup2:
    Is_sameitem = True
    
print(f"same item is {item}")