# -*- coding: utf-8 -*-
"""Lesson9_Bai06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XDdiNzAtLAjOS90EFNmiOKV49hMj48y3
"""



"""Bài 06. Viết hàm
        def is_pangram(str, alphabet)
    đề kiểm tra xem chuỗi str có phải là Pangram không, trả lại True nếu có, False nếu không
    Ghi chú: Pangram là chuỗi chứa mỗi chữ cái trong bảng alphabet ít nhất 1 lần
"""

def is_pangram(string,alphabet):
  for char in alphabet:
    if char not in string:
      return False
  return True

string = "the quick browne fox jumps over the lazy dog"
alphabet = "qwertyuiopasdfghjklzxcvbnm"

print(is_pangram(string,alphabet))

str1 = " fox jumps over the lazy dog"
alphabet = "qwertyuiopasdfghjklzxcvbnm"

pangram2 = is_pangram(str1,alphabet)
print(pangram2)