# -*- coding: utf-8 -*-
"""Lesson7_Bai01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BCh_QZipzVQNxMwsRUexikY7D9V93n3M
"""

my_tuple = (1,2,3,4)
my_list = list(my_tuple)
print(my_list)

