# -*- coding: utf-8 -*-
"""Lesson5_bai6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRv4cLmcyR34V4T6nVb7vivacLIh75Fi
"""

s = input("input any string!: ")
char = input("enter any char ")          
for i in range(len(s)):
  if s[i] == char:
    print(f"the index of {char} is {i}")

