# -*- coding: utf-8 -*-
"""Lesson6_Bai02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqkFXajf2dQBMaMaA75Z7FhjyhuczI4X
"""



"""Viết chương trình tìm số lớn nhất, nhỏ nhất trong một list."""

my_list = [10, 3, 23, 45, 69]
smallest = my_list[0]
biggest = my_list[0]
for number in range(len(my_list)):
  if smallest > my_list[number]:
    smallest = my_list[number]
  elif biggest < my_list[number]:
    biggest = my_list[number]

print(f"The smallest number in the list is :{smallest}")
print(f"The biggest number in the list is :{biggest}")