# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pR7tg8h3SoC4chqdKcNjYoTaPFQypXLg
"""



"""Bài 13. Viết hàm
        def find_x(a_list, x)
    trả lại tất cả các vị trí mà x xuất hiện trong a_list, nếu không có thì trả lại -1
"""

def find_x(a_list,x):
  for item in range(len(a_list)):
    if x == a_list[item]:
      return a_list[item]
    elif x != a_list[item]:
      return -1 

findX = find_x([1,1,3,4],1)
print(findX)