# -*- coding: utf-8 -*-
"""Lesson6_bai6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRv4cLmcyR34V4T6nVb7vivacLIh75Fi
"""

s = input("input any string!: ")
char = input("input any char in that that string ")
print("To check if any char in string's': ")
for i in range(len(s)):
  if s[i] == char:
    print(f"characters in string = {char}")

