# -*- coding: utf-8 -*-
"""Lesson9_Bai03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fxe8vsZNEkHiHUzqA4Ve6NYMFVqi_tib
"""



"""Bài 03. Viết hàm
        def is_perfect(n)
    để kiểm tra xem số tự nhiên n có phải là số hoàn hảo hay ko, trả lại True nếu có, False nếu không.
"""

def is_perfect(n):
  sum = 0
  for i in range(1,n):
    if n % i == 0:
      sum = sum + i
  if sum == n:
    return True
  else:
    return False

number = int(input("Enter number and check if the number is perfect number: "))
Perfect = is_perfect(number)
print(Perfect)