# -*- coding: utf-8 -*-
"""Lesson5_Bai2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hiqbcXNgXZNgT8IoVvnfH3PMSEUlvVcj
"""

str = input("Enter the string:\n")
if len(str) < 2:
  print("")
else:
  str1= str[:2]+str[-2:]
  print(str1)

