# -*- coding: utf-8 -*-
"""Lesson8_Bai07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mc2qATZd-wVnfe7hyCK-oz4GxaBCoZpu
"""



"""Bài 07. Viết hàm đếm số lần xuất hiện các ký tự trong một String"""

str = input("Enter the string: ")

dict1 = {}
for char in str:
  my_dict = dict1.values()
  if char in my_dict:
    dict1[char] += 1
  else:
    dict1[char] = 1
print(dict1)