# -*- coding: utf-8 -*-
"""Lesson4_Bai5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yAb5oV22Mk-rIGyLg9VsQ79Up00t2OSl
"""



"""Bài 05. Lập chương trình thực hiện các công việc sau:
    1. Nhập số epsilon < 1 từ bàn phím
    2. Tính e = 1 + 1/1! + 1/2! + ... + 1/n! quá trình dừng khi 1/n! < epsilon.
    3. Đưa kết quả ra màn hình
"""

import math
epsilon = float(input("Nhap so epsilon: "))
e = 0
i = 0
while 1/math.factorial(i) >= epsilon:
  e = e + 1/math.factorial(i)
  i = i + 1

print(f"e ~ {e}")