# -*- coding: utf-8 -*-
"""Lesson6_Bai01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-K1QfcOSD0bs8MxMRmYKqALEt5PdwoAu
"""



"""# Viết chương trình tính tổng, tích của các phần tử trong một list."""

my_list = [2, 4, 7, 8]
sum_list = 0
multiply_list = 1
for item in my_list:
  sum_list = sum_list + item
  multiply_list = multiply_list * item
print(f"sum of the list is: {sum_list}")
print(f"multiplication of the list is: {multiply_list}")

