# -*- coding: utf-8 -*-
"""Lesson5_Bai3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OF4RsYL5osoolMZ_611Z86t3mROFjnuD
"""



"""Bài 03. Viết chương trình tìm ra ký tự lớn nhất và ký tự nhỏ nhất của một chuỗi nhập từ bán phím.

"""

str = input("Enter the string:")
print(f"the largest character in ASCII table of this string is {max(str)}")
print(f"the smallest character in ASCII table of this string is {min(str)}")

str = input("Enter the string: ")
print(min(str))

