# -*- coding: utf-8 -*-
"""Lesson10_Bai00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fKczeDLwjzbl8XFDmoGe4J1aryuW3tl
"""



"""Bài 00. Mô phỏng lại trò chơi sau: 
- Người chơi tung 2 con xúc xắc 6 mặt, các mặt có số chấm là: 1, 2, 3, 4, 5, 6
- Quan sát kết quả, tính tổng các mặt hướng lên sau khi 2 con xúc xắc đứng yên
- Lần đầu tiên,
    - Nếu tổng là 7 hoặc 11 => Người chơi THẮNG
    - Nếu tổng là 2, 3 hoặc 12 => Người chơi THUA
    - Nếu tổng là 4, 5, 6, 8, 9 hoặc 10 => Đây sẽ là ĐIỂM của người chơi, và sang vòng tiếp theo
- Để giành được THẮNG, người chơi tiếp tục tung 2 con xúc xắc cho đến khi ra được tổng = ĐIỂM trong lần đầu tiên; 
nếu tung ra được tổng = 7 => Người chơi THUA
"""

import random

def roll1():
  return random.randrange(1,7)

def roll2():
  return random.randrange(1,7)

def roll_combined():
  return roll1() + roll2()

roll = roll_combined()
print(roll)

if roll == 4 or roll == 5 or roll == 6 or roll == 8 or roll == 9 or roll == 10:
    print("Sang vong tiep theo")
    print("Ready for next dice roll")
    while True:
        roll_final = roll1() + roll2()
        if roll_final == 7:
            print(f"Its {roll_final}, You lose")
            break
        elif roll_final == roll:
            print(f"its {roll_final}, you WIN!!!!")
            break
        else:
            print(f"{roll_final} is != {roll}, KEEP GOING !!!")
elif roll == 7 or roll == 11:
    print("You win from first round!!!")  
elif roll == 2 or roll == 3 or roll == 12:
    print("You lose from first round")