# -*- coding: utf-8 -*-
"""Lesson5_Bai5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VtS8WzPrFoChUaqLqS9iHOHhxk_PL2HB
"""

str = input("Nhap vao 1 string bat ki :!")
for number_char in str:
  if '0' <= number_char <= '9':
    print(number_char,end="")

