# -*- coding: utf-8 -*-
"""Lesson7_Bai09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vWZpE-vaw_FVMAcUlUPwpv_cC6i-u6ng
"""



"""Bài 09: Viết chương trình tính tổng và tìm giá trị lớn nhất trong tuple chứa các số thực."""

my_tuple = 1.0, 10.0, 3.5, 4.6, 1.10
print(type(my_tuple))
sum = 0.0

for item in my_tuple:
  sum = sum + item # tinh tong tuple
print(f"Sum of number in tuple: {sum}")

# Find largest value in tuple:
max_value = my_tuple[0]
for item in my_tuple:
  if max_value < item:
    max_value = item
print(f"the largest value of tuple is: {max_value}")