# -*- coding: utf-8 -*-
"""Lesson5_bai4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2rHM6xYNZfCC0mLNXCn961xnphrRiYb
"""

str = "Python is amazing"
str1 = str.upper()
str2 = str.lower()
print(str1)
print(str2)

