# -*- coding: utf-8 -*-
"""Lesson9_Bai1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgMYS5-m32f9KI59RFfWAlORHgVvKqw4
"""



"""# New Section

Bài 01. Viết hàm
        def max_min(*numbers)
    trả lại cả giá trị max, min của nhiều số được truyền vào
"""

def max_min(*numbers):
  """Find smallest and biggest number"""
  maxx = max(numbers)
  minn = min(numbers)
  return maxx , minn

maxMin = max_min(1,5,6,-2,10)
print(maxMin)