# -*- coding: utf-8 -*-
"""Lesson9_Bai07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lKERfXouvrzNE8hvJqbwAXgjSCKjkCrD
"""



"""Bài 07. Viết hàm
        def body_mass_index(m, h)
    để tính toán chỉ số BMI của một người với cân nặng m (kg), chiều cao h (m)
      Viết hàm
        def bmi_information(m, h)
    để đưa ra thông tin về chỉ số BMI cũng như phân loại mức độ gầy - béo của người cân nặng m, chiều cao h
"""

def body_mass_index(w,h):
  BMI = w /(h*h)
  print(f"You BMI = {BMI}")
  return BMI

def bmi_information(w,h):
  BMI = w /(h*h)
  if BMI < 18.5:
    return "You are under weight"
  elif 18.5 <= BMI <= 25:
    return "You are normal"
  elif BMI > 25:
    return "You are overweight"

weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in m"))
BMI = body_mass_index(weight,height)
BMIcal = bmi_information(weight, height)
print(BMIcal)