# -*- coding: utf-8 -*-
"""Lesson9_Bai08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ReuESDf5KdhUzmAQQgS3_xVKqEk8BsKL
"""



"""Bài 08. Viết hàm
        def change_upper_lower(str)
    chuyển toàn bộ các ký tự in hoa sang in thường và in thường thành in hoa trong str
"""

def change_upper_lower(string):
  str1 = ""
  for char in string:
    if char.islower():
       str1 += char.upper()
    else: 
       str1 += char.lower()
  return str1
  

string ='HUNG manh'
change_upper_lower(string)