# -*- coding: utf-8 -*-
"""Lesson4_Bai3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXefukdFHeCLjzAz0Kw1iEOiatpqInv1
"""



"""Bài 03. Lập chương trình thực hiện các công việc sau:
    1. Nhập 1 số nguyên dương n bất kì (n<1000). Yêu cầu kiểm tra dữ liệu đầu vào, nếu sai yêu cầu nhập lại.
    2. Tính tổng các chữ số của số đó.
    3. Hiển thị kết qủa ra màn hình
"""

n = int(input("Enter number"))
sum = 0
while n > 0 and n < 1000:
  last_digit = n % 10
  sum = sum + last_digit
  n = n//10

print(f"Sum = {sum} ")

