# -*- coding: utf-8 -*-
"""Lesson5_Bai1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWA_b1cNBDKhlsuJqPYHio4zVraqD0Fp
"""

str = "Python is amazing"
replace_str =str.replace('P','$',1)
print(replace_str)

