# -*- coding: utf-8 -*-
"""Lesson7_Bai02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLVmPVwgDwCNOOYtYEo_sj4CCPBJHmwd

Bài 02: Viết chương trình đảo ngược một tuple.
"""

x = (1,2,3,4)
print(type(x))

y = reversed(x)
print(tuple(y))

